# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-cart
    ports:
      - "6379:6379"

  cart-service:
    build: .
    container_name: cart-service
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - redis
